INSERT INTO `bsit2` (`subject_code`, `subject`, `units`, `pre_req`) VALUES
('IT 210', 'Data Structures & Algorithms - LEC', 3, 'IT 120'),
('IT 211', 'Web Design & Development - LEC', 3, 'IT 121'),
('IT 212', 'Digital Logic Design - LEC', 3, 'IT 120'),
('IT 220', 'Object-Oriented Programming - LEC', 3, 'IT 210'),
('IT 221', 'Networking - LEC', 3, 'IT 110'),
('IT 222', 'Database Management - LEC', 3, 'IT 210'),
('IT 223', 'Information Management - LEC', 3, 'IT 222'),
('IT 320', 'System Analysis & Design - LEC', 3, 'IT 223'),
('ITTEL1', 'IT Track Elective - LEC', 3, '3rd Year Level'),
('IT 210L', 'Data Structures & Algorithms - LAB', 3, 'IT 120'),
('IT 211L', 'Web Design & Development - LAB', 3, 'IT 121'),
('IT 212L', 'Digital Logic Design - LAB', 3, 'IT 120'),
('IT 220L', 'Object-Oriented Programming - LAB', 3, 'IT 210'),
('IT 221L', 'Networking - LAB', 3, 'IT 110'),
('IT 222L', 'Database Management - LAB', 3, 'IT 210'),
('IT 223L', 'Information Management - LAB', 3, 'IT 222'),
('IT 320L', 'System Analysis & Design - LAB', 3, 'IT 223'),
('ITTEL1L', 'IT Track Elective - LAB', 3, '3rd Year Level'),
('CW', 'The Contemporary World', 3, '-'),
('ArtApp', 'Art Appreciation', 3, '-'),
('PATHFIT 3', 'Individual/Dual Sports', 2, 'PE 2'),
('PATHFIT 4', 'Team Sports', 2, 'PE 3'),
('ACCTG', 'Fundamentals of Accounting', 6, '-'),
('STS', 'Science, Technology & Society', 3, '-'),
('Ethics', 'Ethics', 3, '-');
