INSERT INTO `bsit3` (`subject_code`, `subject`, `units`, `pre_req`) VALUES
('ITELEC2', 'IT Elective II - LEC', 3, 'IT Elec 1'),
('ITELEC1', 'IT ELECTIVE I - LEC', 3, '3rd Year Level'),
('IT310', 'Applications Development and Emerging Technologies - LEC', 3, 'IT220'),
('IT311', 'Operating Systems - LEC', 3, 'IT 221'),
('IT312', 'Human Computer Interaction - LEC', 3, 'IT220'),
('IT321', 'Information Assurance & Security - LEC', 3, 'IT310'),
('IT322', 'Systems Integration & Architecture - LEC', 3, '3rd Year Level'),
('IT323', 'Capstone Project I - LEC', 3, '4th Year Level'),
('IT324', 'Social Issues and Professional Practices', 3, '4th Year Level'),
('ITTEL2', 'IT Track Elective II - LEC', 3, 'ITTEL 1'),

('ITELEC2L', 'IT Elective II - LAB', 3, 'IT Elec 1'),
('ITELEC1L', 'IT ELECTIVE I - LAB', 3, '3rd Year Level'),
('IT310L', 'Applications Development and Emerging Technologies', 3, 'IT220'),
('IT311L', 'Operating Systems - LAB', 3, 'IT 221'),
('IT312L', 'Human Computer Interaction - LAB', 3, 'IT220'),
('IT321L', 'Information Assurance & Security - LAB', 3, 'IT310'),
('IT322L', 'Systems Integration & Architecture - LAB', 3, '3rd Year Level'),
('IT323L', 'Capstone Project I - LAB', 3, '4th Year Level'),
('IT324L', 'Social Issues and Professional Practices', 3, '4th Year Level'),
('ITTEL2L', 'IT Trackk Elective II - LAB', 3, 'ITTEL 1'),
('MMG', 'Marketing Media Gamification', 3, '-'),
('RIZAL', 'Rizal\'s Life & Works', 3, '-'),
('STAT', 'Statistics & Probability', 3, 'MATH Prep'),
('TECHNO', 'Technopreneurship', 3, '-');
