INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ETHICS', 'Ethics', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('RIZAL', 'Rizal\'s Life & Works', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MST', 'Mathematics, Science & Technology', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'Teaching Profession', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 214', 'Teaching & Assessment of Lit.', 3, 'EL 102');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 215', 'Teaching & Assessment of the Macroskills', 3, 'EL 101');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 216', 'Teaching & Assessment of Grammar', 3, 'EL 102');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 217', 'Speech & Theatre Arts', 3, '102');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('CREWRI', 'Creative Writing', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 227', 'Language Education Research ', 3, 'EL 121');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ELT 228', 'Technical Writing', 3, 'ELT 102');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('LIT 201', 'Children & Adolescent Literature', 3, 'ELT 121');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('LIT 202', 'Mythodology & Folklore', 3, 'EL 101');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ARTHUM', 'Arts & Humanities', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 221', 'The Teacher and the Community, School Culture & Organizational Leadership', 3, '-');
INSERT INTO `bsed2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222', 'Foundation of Special & Inclusive Education', 3, '-');
