INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('HIST', 'Reading in Philippine History', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('STS', 'Science, Technology and Society', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('PE 1', 'Physical Education 1', 2, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EL 100', 'Introduction to Linguistics', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('FIL 1', 'Retorika', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('NSTP 1', 'National Service Training Program 1', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EL 102', 'Structures in English', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('PURCOM', 'Purposive Communication', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('UTS', 'Understanding the Self', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 122', 'Language Programs & Policies in Multulingual Societies', 3, 'ELT 121', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 123', 'Language Learning Materials Development', 3, 'EL 101', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ARTAPP', 'Art Appreciation', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('MATHWORLD', 'Mathematics in the Modern World', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 101', 'The Child & Adolescent Learners & Learning Principles', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('NSTP 2', 'National Service Training Program 2', 3, 'NSTP 1', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('PE 2', 'Physical Education 2', 2, 'PE 1',1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('CW', 'The Contemporary World', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('FIL 2', 'Panitikan ng Pilipinas', 3, '-', 1);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ETHICS', 'Ethics', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('RIZAL', "Rizal's Life & Works", 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('MST', 'Mathematics, Science & Technology', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 211', 'Teaching Profession', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 214', 'Teaching & Assessment of Lit.', 3, 'EL 102', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 215', 'Teaching & Assessment of the Macroskills', 3, 'EL 101', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 216', 'Teaching & Assessment of Grammar', 3, 'EL 102', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 217', 'Speech & Theatre Arts', 3, '102', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('CREWRI', 'Creative Writing', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 227', 'Language Education Research ', 3, 'EL 121', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 228', 'Technical Writing', 3, 'ELT 102', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('LIT 201', 'Children & Adolescent Literature', 3, 'ELT 121', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('LIT 202', 'Mythodology & Folklore', 3, 'EL 101', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ARTHUM', 'Arts & Humanities', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 221', 'The Teacher and the Community, School Culture & Organizational Leadership', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 222', 'Foundation of Special & Inclusive Education', 3, '-', 2);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 313', 'Facilitating Learner-Centered Teaching', 3, 'EDUC 101', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('SOCPHIL', 'Social Science and Philosophy', 3, '-', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 311', 'Assessment in Learning 1', 3, 'EDUC 101', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('LIT 316', 'Contemporary, Popular & Emergement Literature', 2, 'LIT 201',3 );
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('LIT 315', 'Survey of English & American Literature', 3, 'LIT 201', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 314', 'Survey of Afro-Asian Literature', 3, 'LIT 201', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ELT 313', 'Survey of Phil. Literature in English', 3, 'LIT 201', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 312', 'Technology for Teaching and Learning 1', 3, 'EDUC 211', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 324', 'Bulding & Enhancing New Literacies Accross the Curriculum', 3, 'ELT 121', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 321', 'Assessment in Learning 2', 3, 'EDUC 311', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 322', 'Technology for Teaching and Learning 2', 3, 'EDUC 312', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('EDUC 323', 'The Teacher and the School Curriculum ', 3, 'EDUC 211', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('CAMJOUR', 'Campus Journalism', 3, 'ELT 228', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('RGEC 1 ', 'Review on General Education Cources', 3, '3Y STANDING', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('LIT 327', 'Literacy Critism', 3, 'LIT 313, LIT 314, LIT 315, LIT 316', 3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('ESP 100', 'English for Special Purpose', 3, '-',3);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('FS 1', 'Field Study 1', 3, '4Y STANDING', 4);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('FS 2', 'Field Study 2', 3, '4Y STANDING', 4);
INSERT INTO `bsed`(`subject_code`, `subject`, `units`, `pre_req`, `year`) VALUES ('RGEC 2 ', 'Review on Professional Education Courses', 3, 'RGEC 1', 4);
