INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('RES 100', 'Research in Education', 3, '3Y STANDING');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 313', 'Facilitating Learner-Centered Taching', 3, 'EDUC 101');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ARTS 100', 'Teaching Arts in Elem.', 3, '-');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 312', 'Technology for Teaching and Learning 1', 3, 'EDUC 211');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('TLE 311', 'Edukasyong Pantahanan at Pankabuhayan', 3, '-');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MUSIC 100', 'Teaching Music in the Elementary Grades', 3, 'EDUC 101');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 311', 'Assesment in Learning 1', 3, '-');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('RGEC 1', 'Review on General Education Courses', 3, '3Y STANDING');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('TLE 322', 'Edukasyong Pantahanan at Pangkabuhayan w/Enrep. ', 3, 'TLE 311');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PEH 100', 'Teaching PE and Health in the Elementary Grades', 3, '-');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 321', 'Assessment in Learning 2', 3, 'EDUC 311');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 322', 'Technology for Teaching and Learning 2', 3, 'EDUC 312');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 333', 'The Teacher & the School Curriculum', 3, 'EDUC 211');
INSERT INTO `bselem3`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 324', 'Building & Enhancing New Literature Across the Curriculum', 3, 'TLE 311');
