INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('HIST', 'Reading in Phillipine History', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MST', 'Mathematics, Science & Technology', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SOCPHIl', 'Social Science & Technology', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 1', 'Physical Education 1', 2, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('NSTP 1 ', 'National Service Training Program 1', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('STS', 'Science, Technology & Society', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('RIZAL', 'Rizal\'s Life & Works', 2, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 1', 'Retorika ', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PURCOM ', 'Purposive Communication', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('UTS', 'Understanding the Self', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 2', 'Panitikan ng Pilipinas', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ETHICS', 'Ethics', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ARTAPP', 'Art Appreciation', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATHWORLD', 'Mathematics in Modern World', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 101', 'The Child & Adolescent Learners & Learning Principles', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ARTHUM ', 'Arts and Humanities', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MTB 10', 'Content & Pedagogy for the Mother Tongue', 2, 'PE 1');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('CW', 'Contemporary World', 3, '-');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('NSTP 2', 'National Service Training Program 2', 3, 'NSTP 1');
INSERT INTO `bselem1`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 2 ', 'Physical Education 2', 2, 'PE 1');
