INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('VED 100', 'Good Maners and Right Conduct', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSC 211', 'Teaching Social Studies in the Elementary Grades (Phil. History & Goverment)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 221', 'Teaching Math in Primary Grades', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'The Teaching Profession', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSI 211', 'Teaching Science in the Elemtary Grades (Biology and Chemistry)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENG 211', 'Teaching English in the Elem. Grades (Language Arts)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222 ', 'Foundation of Special & Inclusive Education', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 4', 'Physical Education 4', 2, 'PE 3');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SCI 222', 'Teaching Science in the Elementary Grades (Physics, Earth & Space Science', 3, 'SCI 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 222', 'Teaching Math in the Intermediate Class', 3, 'MATH 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 222', 'Pagtuturo ng Filipino sa Elem. 2 (Panitikan ng Pilipinas) ', 3, 'FIL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENGL 222 ', 'Teaching English in the Elem. Grades Through Literature', 3, 'ENGL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('VED 100', 'Good Maners and Right Conduct', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSC 211', 'Teaching Social Studies in the Elementary Grades (Phil. History & Goverment)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 221', 'Teaching Math in Primary Grades', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'The Teaching Profession', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSI 211', 'Teaching Science in the Elemtary Grades (Biology and Chemistry)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENG 211', 'Teaching English in the Elem. Grades (Language Arts)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222 ', 'Foundation of Special & Inclusive Education', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 4', 'Physical Education 4', 2, 'PE 3');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SCI 222', 'Teaching Science in the Elementary Grades (Physics, Earth & Space Science', 3, 'SCI 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 222', 'Teaching Math in the Intermediate Class', 3, 'MATH 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 222', 'Pagtuturo ng Filipino sa Elem. 2 (Panitikan ng Pilipinas) ', 3, 'FIL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENGL 222 ', 'Teaching English in the Elem. Grades Through Literature', 3, 'ENGL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('VED 100', 'Good Maners and Right Conduct', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSC 211', 'Teaching Social Studies in the Elementary Grades (Phil. History & Goverment)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 221', 'Teaching Math in Primary Grades', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'The Teaching Profession', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSI 211', 'Teaching Science in the Elemtary Grades (Biology and Chemistry)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENG 211', 'Teaching English in the Elem. Grades (Language Arts)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222 ', 'Foundation of Special & Inclusive Education', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 4', 'Physical Education 4', 2, 'PE 3');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SCI 222', 'Teaching Science in the Elementary Grades (Physics, Earth & Space Science', 3, 'SCI 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 222', 'Teaching Math in the Intermediate Class', 3, 'MATH 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 222', 'Pagtuturo ng Filipino sa Elem. 2 (Panitikan ng Pilipinas) ', 3, 'FIL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENGL 222 ', 'Teaching English in the Elem. Grades Through Literature', 3, 'ENGL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('VED 100', 'Good Maners and Right Conduct', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSC 211', 'Teaching Social Studies in the Elementary Grades (Phil. History & Goverment)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 221', 'Teaching Math in Primary Grades', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'The Teaching Profession', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSI 211', 'Teaching Science in the Elemtary Grades (Biology and Chemistry)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENG 211', 'Teaching English in the Elem. Grades (Language Arts)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222 ', 'Foundation of Special & Inclusive Education', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 4', 'Physical Education 4', 2, 'PE 3');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SCI 222', 'Teaching Science in the Elementary Grades (Physics, Earth & Space Science', 3, 'SCI 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 222', 'Teaching Math in the Intermediate Class', 3, 'MATH 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 222', 'Pagtuturo ng Filipino sa Elem. 2 (Panitikan ng Pilipinas) ', 3, 'FIL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENGL 222 ', 'Teaching English in the Elem. Grades Through Literature', 3, 'ENGL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('VED 100', 'Good Maners and Right Conduct', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSC 211', 'Teaching Social Studies in the Elementary Grades (Phil. History & Goverment)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 221', 'Teaching Math in Primary Grades', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 211', 'The Teaching Profession', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SSI 211', 'Teaching Science in the Elemtary Grades (Biology and Chemistry)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 3', 'Physical Education 3', 2, 'PE 2');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENG 211', 'Teaching English in the Elem. Grades (Language Arts)', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('EDUC 222 ', 'Foundation of Special & Inclusive Education', 3, '-');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('PE 4', 'Physical Education 4', 2, 'PE 3');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('SCI 222', 'Teaching Science in the Elementary Grades (Physics, Earth & Space Science', 3, 'SCI 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('MATH 222', 'Teaching Math in the Intermediate Class', 3, 'MATH 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('FIL 222', 'Pagtuturo ng Filipino sa Elem. 2 (Panitikan ng Pilipinas) ', 3, 'FIL 221');
INSERT INTO `bselem2`(`subject_code`, `subject`, `units`, `pre-req`) VALUES ('ENGL 222 ', 'Teaching English in the Elem. Grades Through Literature', 3, 'ENGL 221');
